package com.guandian.bidding.module.audit.enums;

public enum OperationAction {
    CREATE,
    PUBLISH,
    UPDATE,
    ABORT,
    ARCHIVE,
    OPEN_START,
    AUDIT,
    PAY,
    SUBMIT,
    ENCRYPT,
    WITHDRAW,
    DECRYPT,
    DRAW_EXPERT,
    SIGN_IN,
    REVIEW,
    SCORE,
    ELECT_LEADER,
    NEGOTIATION,
    SECOND_QUOTE,
    REPORT_EDIT,
    REPORT_PUSH,
    REPORT_SIGN,
    AWARD_PUBLISH,
    AGENCY_FEE_PUSH,
    NOTICE_PUBLISH,
    ROLE_AUDIT,
    TENDERER_INVITE,
    TENDERER_ACCEPT,
    TENDERER_REJECT,
    FEEDBACK
}
